name: Verify Commit
on:
  push:
    branches: ['*']
  pull_request:
    branches: [main]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install modules
        run: npm install

      - name: Run build
        run: npm run build

      - name: Run TypeScript compiler ESLint
        run: npm run lint

      - name: Run Markdown Lint
        run: npm run lint:markdown

      - name: Run Jest
        run: npm run test

      - name: Archive verified build
        uses: actions/upload-artifact@v3
        with:
          name: dist-verified
          path: |
            main.js
            manifest.json

